# This file lists variables used in configuring dc1 evaluation 
################################################################
## Net variables
glonet_base_url: "https://minio.dive.edito.eu"
glonet_s3_bucket: "project-glonet"
s3_glonet_folder: "public/glonet_reforecast_2024"
glorys_cmems_product_name: "cmems_mod_glo_phy_myint_0.083deg_P1D-m"
glonet_n_days_forecast: 10

glonet_local_dir: "/home/k24aitmo/IMT/software/tests/Glonet"
max_samples: 2
###########################################
## List of start time for TC events
start_times:
   - "1900-01-01"
   - "2021-07-01"
## List of end time for TC events 
end_times:
   - "2026-01-01"
   - "2021-07-02"

# lead time definition (hours)
lead_time_start: "0"
lead_time_stop: "240"
lead_time_frequency: "24"

# variables for evaluation data targets
target_vars:
  - "uo"
  - "vo"
  - "zos"
  - "thetao"
  - "so"
  
#vents 	de surface (sortie) / observations satellitaires (SAR) du vent à haute résolution (référence)
#variables représentatives des vagues de surface (haute résolution) : 	SSH, SST, SSS, couleur de l’océan (sortie) / observations satellite et réanalyses (modèles ERA-5 et Mercator-GLORYS)	(référence)
#distribution de la salinité et de la température de la couche supérieure de l'océan (sortie du modèle) / profils ARGO et réanalyses (modèle Mercator-GLORYS) (référence)


# variables for evaluation data inputs
input_vars: "*"
#variables (SSH, vents de surface, vagues, précipitations, température 	intérieure et de surface, couleur de l’océan) avant, pendant, 	après le passage du cyclone.
#conditions de la haute mer avant la tempête (par exemple, SST, SSS, densité 	verticale de la haute mer, force de stratification, etc.)
#forçages atmosphériques pendant le passage du cyclone (vent maximum, pluie accumulée et 	évaporation, indice de puissance éolienne, etc..)
#sillages océaniques laissés après la tempête pour un ensemble de variables (SST, SSS, hauteur du niveau de la mer, paramètres de couleur de l'océan).
#réanalyses : atmosphérique, océanique, des caractéristiques du vortex.

# Target region coordinates
min_lat: -100
max_lat: 100
min_lon: -100
max_lon: 100

# Path to catalog file
catalog_path: ""

# Datasets
batch_size: 8

sources:
  - url: "https://minio.dive.edito.eu"
    s3_bucket: "project-glonet"
    s3_folder: "public/glonet_reforecast_2024"
    dataset: GLONET
    scanner: scanners.s3_scanner

  - url: ""
    cmems_product_name: "cmems_mod_glo_phy_myint_0.083deg_P1D-m"
    dataset: GLORYS
    scanner: scanners.cmems_scanner
    
# Wasabi S3 storage info
wasabi_bucket: "ppr-ocean-climat"
wasabi_glonet_folder: "DC1/Glonet_forecast"
wasabi_key: 
wasabi_secret_key: 
wasabi_endpoint_url: "https://s3.eu-west-2.wasabisys.com"

