# This file lists variables used in configuring dc1 evaluation 
################################################################
## 

glonet_n_days_forecast: 10

max_samples: 2
###########################################
## List of start time for TC events
start_times:
   - "2024-01-01"
## List of end time for TC events 
end_times:
   - "2025-01-01"

# lead time definition (hours)
lead_time_start: "0"
lead_time_stop: "240"
lead_time_frequency: "24"

# variables for evaluation data targets
target_vars:
  - "uo"
  - "vo"
  - "zos"
  - "thetao"
  - "so"
  
#vents 	de surface (sortie) / observations satellitaires (SAR) du vent à haute résolution (référence)
#variables représentatives des vagues de surface (haute résolution) : 	SSH, SST, SSS, couleur de l’océan (sortie) / observations satellite et réanalyses (modèles ERA-5 et Mercator-GLORYS)	(référence)
#distribution de la salinité et de la température de la couche supérieure de l'océan (sortie du modèle) / profils ARGO et réanalyses (modèle Mercator-GLORYS) (référence)


# variables for evaluation data inputs
input_vars: "*"
#variables (SSH, vents de surface, vagues, précipitations, température 	intérieure et de surface, couleur de l’océan) avant, pendant, 	après le passage du cyclone.
#conditions de la haute mer avant la tempête (par exemple, SST, SSS, densité 	verticale de la haute mer, force de stratification, etc.)
#forçages atmosphériques pendant le passage du cyclone (vent maximum, pluie accumulée et 	évaporation, indice de puissance éolienne, etc..)
#sillages océaniques laissés après la tempête pour un ensemble de variables (SST, SSS, hauteur du niveau de la mer, paramètres de couleur de l'océan).
#réanalyses : atmosphérique, océanique, des caractéristiques du vortex.

# Target region coordinates
min_lat: -90
max_lat: 90
min_lon: -180
max_lon: 180

# Path to catalog file
catalog_path: ""

# Datasets
batch_size: 8

sources:
  - dataset: glonet
    config: "s3"
    connection_type: "glonet"
    url: "https://minio.dive.edito.eu"
    s3_bucket: "project-glonet"
    s3_folder: "public/glonet_refull_2024"

  - dataset: glorys
    config: "cmems"
    connection_type:
    cmems_product_name: "cmems_mod_glo_phy_myint_0.083deg_P1D-m"

  - dataset: glonet_wasabi
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC1/Glonet_forecast"
    s3_key: 
    s3_secret_key: 

